### ISSUE TITLE
code_executor does not implement tolerations

### ISSUE THREAD

**Issue by akitson-degreed** [tryretool/retool-helm#138]
https://github.com/tryretool/retool-helm/blob/main/charts/retool/templates/deployment_code_executor.yaml

The deployment for the code executor does not set tolerations.

This is set in each of the other deployments, but not here.  And since it isn't, nodes are getting scheduled in the wrong node pools.

**Comment by Pixis-Akshay-Gopani** [comment]
Any update on this ??

**Comment by chawleejay** [comment]
any update on this??

**Comment by bwmetcalf** [comment]
Any update?  Experiencing the same issue.

**Comment by roberto-retool** [comment]
fixed by https://github.com/tryretool/retool-helm/pull/180
