### ISSUE TITLE
Add escape hatch for extra manifests and support for environment variables from secrets

### ISSUE THREAD

**Issue by gab-nando** [tryretool/retool-helm#34]
It would be extremely handy to have the possibility to:
* Add arbitrary manifests to the chart. One use case is to be able to provision ManagedCertificate, BackendConfig to be used with Google Load Balancer.
* Set environment variables from secret. Helpful, for instance, for setting SCIM_AUTH_TOKEN

**Comment by stpierre** [comment]
Yes please! We'd like to add HPAs, and the inability to pass in env vars from secrets is a pretty substantial oversight. Hopefully this gets attention quickly.

**Comment by rjay98** [comment]
apologies for accidentally assigning - @kyle-retool if you want to take a look!
