### ISSUE TITLE
Ingress path seems to be a bug

### ISSUE THREAD

**Issue by bipinu** [tryretool/retool-helm#41]
Where does the `{{ .path }}` value in [ingress.yaml](https://github.com/tryretool/retool-helm/blob/main/templates/ingress.yaml#L25
) come from?   
Bases on [NOTES.txt](https://github.com/tryretool/retool-helm/blob/main/templates/NOTES.txt#L3), it seems that Values.yaml should have an array of hosts and paths, but [that doesn't seem to be the case](https://github.com/tryretool/retool-helm/blob/main/values.yaml#L92).

**Comment by hafeyang** [comment]
same problem

**Comment by anna-yn** [comment]
Hi! Sorry for the late reply, this should be fixed now by https://github.com/tryretool/retool-helm/commit/81734ea759431f6ce4ee0fa9ce4f8847bd56ebb0 in v4.9.0!
