### ISSUE TITLE
No persistentVolumeClaim found

### ISSUE THREAD

**Issue by hakuno** [tryretool/retool-helm#52]
Where is `persistentVolumeClaim` in the template?

Does it have any sample of how using that?

**Comment by eltioemil** [comment]
@hakuno looks like they [added it](https://github.com/tryretool/retool-helm/commit/b7623b2cab495ecec17e9e86a0c17a3552378b25) to the templates.

**Comment by hakuno** [comment]
> @hakuno looks like they [added it](https://github.com/tryretool/retool-helm/commit/b7623b2cab495ecec17e9e86a0c17a3552378b25) to the templates.

My current employer doesn't use this tool. But I'm happy it has been added. Thanks!
